// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file admin.proto (package admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin.proto.
 */
export const file_admin: GenFile = /*@__PURE__*/
  fileDesc("CgthZG1pbi5wcm90bxIFYWRtaW4iVAoRQ3JlYXRlVXNlclJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSDQoFZW1haWwYAyABKAkSDAoEcm9sZRgEIAEoCSJAChFEZWxldGVVc2VyUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhoKEnJlcXVlc3RpbmdfdXNlcl9pZBgCIAEoCSJQChFVcGRhdGVVc2VyUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhQKDG5ld191c2VybmFtZRgCIAEoCRIUCgxuZXdfcGFzc3dvcmQYAyABKAkiKwoXQWRtaW5EZWxldGVUb3BpY1JlcXVlc3QSEAoIdG9waWNfaWQYASABKAkiMQoNQWRtaW5SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkiWgoEVXNlchIPCgd1c2VyX2lkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEgwKBHJvbGUYBCABKAkSEgoKY3JlYXRlZF9hdBgFIAEoCSJiCgpBZG1pblRvcGljEhAKCHRvcGljX2lkGAEgASgJEgwKBG5hbWUYAiABKAkSDwoHdXNlcl9pZBgDIAEoCRIQCgh1c2VybmFtZRgEIAEoCRIRCglwYXJlbnRfaWQYBSABKAkiEgoQTGlzdFVzZXJzUmVxdWVzdCIvChFMaXN0VXNlcnNSZXNwb25zZRIaCgV1c2VycxgBIAMoCzILLmFkbWluLlVzZXIiJwoUTGlzdEFsbFRvcGljc1JlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSI6ChVMaXN0QWxsVG9waWNzUmVzcG9uc2USIQoGdG9waWNzGAEgAygLMhEuYWRtaW4uQWRtaW5Ub3BpYzKZAwoMQWRtaW5TZXJ2aWNlEjwKCkNyZWF0ZVVzZXISGC5hZG1pbi5DcmVhdGVVc2VyUmVxdWVzdBoULmFkbWluLkFkbWluUmVzcG9uc2USPAoKRGVsZXRlVXNlchIYLmFkbWluLkRlbGV0ZVVzZXJSZXF1ZXN0GhQuYWRtaW4uQWRtaW5SZXNwb25zZRI8CgpVcGRhdGVVc2VyEhguYWRtaW4uVXBkYXRlVXNlclJlcXVlc3QaFC5hZG1pbi5BZG1pblJlc3BvbnNlEj4KCUxpc3RVc2VycxIXLmFkbWluLkxpc3RVc2Vyc1JlcXVlc3QaGC5hZG1pbi5MaXN0VXNlcnNSZXNwb25zZRJDCgtEZWxldGVUb3BpYxIeLmFkbWluLkFkbWluRGVsZXRlVG9waWNSZXF1ZXN0GhQuYWRtaW4uQWRtaW5SZXNwb25zZRJKCg1MaXN0QWxsVG9waWNzEhsuYWRtaW4uTGlzdEFsbFRvcGljc1JlcXVlc3QaHC5hZG1pbi5MaXN0QWxsVG9waWNzUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message admin.CreateUserRequest
 */
export type CreateUserRequest = Message<"admin.CreateUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;
};

/**
 * Describes the message admin.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_admin, 0);

/**
 * @generated from message admin.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"admin.DeleteUserRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string requesting_user_id = 2;
   */
  requestingUserId: string;
};

/**
 * Describes the message admin.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> = /*@__PURE__*/
  messageDesc(file_admin, 1);

/**
 * @generated from message admin.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"admin.UpdateUserRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string new_username = 2;
   */
  newUsername: string;

  /**
   * @generated from field: string new_password = 3;
   */
  newPassword: string;
};

/**
 * Describes the message admin.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> = /*@__PURE__*/
  messageDesc(file_admin, 2);

/**
 * @generated from message admin.AdminDeleteTopicRequest
 */
export type AdminDeleteTopicRequest = Message<"admin.AdminDeleteTopicRequest"> & {
  /**
   * @generated from field: string topic_id = 1;
   */
  topicId: string;
};

/**
 * Describes the message admin.AdminDeleteTopicRequest.
 * Use `create(AdminDeleteTopicRequestSchema)` to create a new message.
 */
export const AdminDeleteTopicRequestSchema: GenMessage<AdminDeleteTopicRequest> = /*@__PURE__*/
  messageDesc(file_admin, 3);

/**
 * @generated from message admin.AdminResponse
 */
export type AdminResponse = Message<"admin.AdminResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message admin.AdminResponse.
 * Use `create(AdminResponseSchema)` to create a new message.
 */
export const AdminResponseSchema: GenMessage<AdminResponse> = /*@__PURE__*/
  messageDesc(file_admin, 4);

/**
 * @generated from message admin.User
 */
export type User = Message<"admin.User"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;
};

/**
 * Describes the message admin.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_admin, 5);

/**
 * @generated from message admin.AdminTopic
 */
export type AdminTopic = Message<"admin.AdminTopic"> & {
  /**
   * @generated from field: string topic_id = 1;
   */
  topicId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: string username = 4;
   */
  username: string;

  /**
   * @generated from field: string parent_id = 5;
   */
  parentId: string;
};

/**
 * Describes the message admin.AdminTopic.
 * Use `create(AdminTopicSchema)` to create a new message.
 */
export const AdminTopicSchema: GenMessage<AdminTopic> = /*@__PURE__*/
  messageDesc(file_admin, 6);

/**
 * @generated from message admin.ListUsersRequest
 */
export type ListUsersRequest = Message<"admin.ListUsersRequest"> & {
};

/**
 * Describes the message admin.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export const ListUsersRequestSchema: GenMessage<ListUsersRequest> = /*@__PURE__*/
  messageDesc(file_admin, 7);

/**
 * @generated from message admin.ListUsersResponse
 */
export type ListUsersResponse = Message<"admin.ListUsersResponse"> & {
  /**
   * @generated from field: repeated admin.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message admin.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema: GenMessage<ListUsersResponse> = /*@__PURE__*/
  messageDesc(file_admin, 8);

/**
 * @generated from message admin.ListAllTopicsRequest
 */
export type ListAllTopicsRequest = Message<"admin.ListAllTopicsRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message admin.ListAllTopicsRequest.
 * Use `create(ListAllTopicsRequestSchema)` to create a new message.
 */
export const ListAllTopicsRequestSchema: GenMessage<ListAllTopicsRequest> = /*@__PURE__*/
  messageDesc(file_admin, 9);

/**
 * @generated from message admin.ListAllTopicsResponse
 */
export type ListAllTopicsResponse = Message<"admin.ListAllTopicsResponse"> & {
  /**
   * @generated from field: repeated admin.AdminTopic topics = 1;
   */
  topics: AdminTopic[];
};

/**
 * Describes the message admin.ListAllTopicsResponse.
 * Use `create(ListAllTopicsResponseSchema)` to create a new message.
 */
export const ListAllTopicsResponseSchema: GenMessage<ListAllTopicsResponse> = /*@__PURE__*/
  messageDesc(file_admin, 10);

/**
 * @generated from service admin.AdminService
 */
export const AdminService: GenService<{
  /**
   * @generated from rpc admin.AdminService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof AdminResponseSchema;
  },
  /**
   * @generated from rpc admin.AdminService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof AdminResponseSchema;
  },
  /**
   * @generated from rpc admin.AdminService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof AdminResponseSchema;
  },
  /**
   * @generated from rpc admin.AdminService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUsersRequestSchema;
    output: typeof ListUsersResponseSchema;
  },
  /**
   * @generated from rpc admin.AdminService.DeleteTopic
   */
  deleteTopic: {
    methodKind: "unary";
    input: typeof AdminDeleteTopicRequestSchema;
    output: typeof AdminResponseSchema;
  },
  /**
   * @generated from rpc admin.AdminService.ListAllTopics
   */
  listAllTopics: {
    methodKind: "unary";
    input: typeof ListAllTopicsRequestSchema;
    output: typeof ListAllTopicsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin, 0);

