// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file auth.proto (package auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvEgRhdXRoIkQKD1JlZ2lzdGVyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRINCgVlbWFpbBgDIAEoCSIyCgxMb2dpblJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiJQoUVmFsaWRhdGVUb2tlblJlcXVlc3QSDQoFdG9rZW4YASABKAkiRQoVVmFsaWRhdGVUb2tlblJlc3BvbnNlEg0KBXZhbGlkGAEgASgIEg8KB3VzZXJfaWQYAiABKAkSDAoEcm9sZRgDIAEoCSJfCgxBdXRoUmVzcG9uc2USDQoFdG9rZW4YASABKAkSDwoHdXNlcl9pZBgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCRIMCgRyb2xlGAQgASgJEg8KB21lc3NhZ2UYBSABKAkyvwEKC0F1dGhTZXJ2aWNlEjUKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaEi5hdXRoLkF1dGhSZXNwb25zZRIvCgVMb2dpbhISLmF1dGguTG9naW5SZXF1ZXN0GhIuYXV0aC5BdXRoUmVzcG9uc2USSAoNVmFsaWRhdGVUb2tlbhIaLmF1dGguVmFsaWRhdGVUb2tlblJlcXVlc3QaGy5hdXRoLlZhbGlkYXRlVG9rZW5SZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message auth.RegisterRequest
 */
export type RegisterRequest = Message<"auth.RegisterRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth, 0);

/**
 * @generated from message auth.LoginRequest
 */
export type LoginRequest = Message<"auth.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * @generated from message auth.ValidateTokenRequest
 */
export type ValidateTokenRequest = Message<"auth.ValidateTokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message auth.ValidateTokenRequest.
 * Use `create(ValidateTokenRequestSchema)` to create a new message.
 */
export const ValidateTokenRequestSchema: GenMessage<ValidateTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth, 2);

/**
 * @generated from message auth.ValidateTokenResponse
 */
export type ValidateTokenResponse = Message<"auth.ValidateTokenResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string role = 3;
   */
  role: string;
};

/**
 * Describes the message auth.ValidateTokenResponse.
 * Use `create(ValidateTokenResponseSchema)` to create a new message.
 */
export const ValidateTokenResponseSchema: GenMessage<ValidateTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth, 3);

/**
 * @generated from message auth.AuthResponse
 */
export type AuthResponse = Message<"auth.AuthResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: string message = 5;
   */
  message: string;
};

/**
 * Describes the message auth.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse> = /*@__PURE__*/
  messageDesc(file_auth, 4);

/**
 * @generated from service auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.ValidateToken
   */
  validateToken: {
    methodKind: "unary";
    input: typeof ValidateTokenRequestSchema;
    output: typeof ValidateTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth, 0);

