// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file document.proto (package document, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file document.proto.
 */
export const file_document: GenFile = /*@__PURE__*/
  fileDesc("Cg5kb2N1bWVudC5wcm90bxIIZG9jdW1lbnQiSwoVVXBsb2FkRG9jdW1lbnRSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkSEAoIZmlsZW5hbWUYAiABKAkSDwoHY29udGVudBgDIAEoDCI/ChdEb3dubG9hZERvY3VtZW50UmVxdWVzdBITCgtkb2N1bWVudF9pZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIk4KGERvd25sb2FkRG9jdW1lbnRSZXNwb25zZRIQCghmaWxlbmFtZRgBIAEoCRIPCgdjb250ZW50GAIgASgMEg8KB21lc3NhZ2UYAyABKAkiPQoVRGVsZXRlRG9jdW1lbnRSZXF1ZXN0EhMKC2RvY3VtZW50X2lkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkiOgoWRGVsZXRlRG9jdW1lbnRSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkifQoIRG9jdW1lbnQSEwoLZG9jdW1lbnRfaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRIQCghmaWxlbmFtZRgDIAEoCRIQCgh0b3BpY19pZBgEIAEoCRISCgp0b3BpY19uYW1lGAUgASgJEhMKC3VwbG9hZGVkX2F0GAYgASgJIloKEERvY3VtZW50UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJEiQKCGRvY3VtZW50GAMgASgLMhIuZG9jdW1lbnQuRG9jdW1lbnQiOQoUTGlzdERvY3VtZW50c1JlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCRIQCgh0b3BpY19pZBgCIAEoCSI+ChVMaXN0RG9jdW1lbnRzUmVzcG9uc2USJQoJZG9jdW1lbnRzGAEgAygLMhIuZG9jdW1lbnQuRG9jdW1lbnQy4gIKD0RvY3VtZW50U2VydmljZRJNCg5VcGxvYWREb2N1bWVudBIfLmRvY3VtZW50LlVwbG9hZERvY3VtZW50UmVxdWVzdBoaLmRvY3VtZW50LkRvY3VtZW50UmVzcG9uc2USWQoQRG93bmxvYWREb2N1bWVudBIhLmRvY3VtZW50LkRvd25sb2FkRG9jdW1lbnRSZXF1ZXN0GiIuZG9jdW1lbnQuRG93bmxvYWREb2N1bWVudFJlc3BvbnNlElAKDUxpc3REb2N1bWVudHMSHi5kb2N1bWVudC5MaXN0RG9jdW1lbnRzUmVxdWVzdBofLmRvY3VtZW50Lkxpc3REb2N1bWVudHNSZXNwb25zZRJTCg5EZWxldGVEb2N1bWVudBIfLmRvY3VtZW50LkRlbGV0ZURvY3VtZW50UmVxdWVzdBogLmRvY3VtZW50LkRlbGV0ZURvY3VtZW50UmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message document.UploadDocumentRequest
 */
export type UploadDocumentRequest = Message<"document.UploadDocumentRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string filename = 2;
   */
  filename: string;

  /**
   * @generated from field: bytes content = 3;
   */
  content: Uint8Array;
};

/**
 * Describes the message document.UploadDocumentRequest.
 * Use `create(UploadDocumentRequestSchema)` to create a new message.
 */
export const UploadDocumentRequestSchema: GenMessage<UploadDocumentRequest> = /*@__PURE__*/
  messageDesc(file_document, 0);

/**
 * @generated from message document.DownloadDocumentRequest
 */
export type DownloadDocumentRequest = Message<"document.DownloadDocumentRequest"> & {
  /**
   * @generated from field: string document_id = 1;
   */
  documentId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message document.DownloadDocumentRequest.
 * Use `create(DownloadDocumentRequestSchema)` to create a new message.
 */
export const DownloadDocumentRequestSchema: GenMessage<DownloadDocumentRequest> = /*@__PURE__*/
  messageDesc(file_document, 1);

/**
 * @generated from message document.DownloadDocumentResponse
 */
export type DownloadDocumentResponse = Message<"document.DownloadDocumentResponse"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: bytes content = 2;
   */
  content: Uint8Array;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message document.DownloadDocumentResponse.
 * Use `create(DownloadDocumentResponseSchema)` to create a new message.
 */
export const DownloadDocumentResponseSchema: GenMessage<DownloadDocumentResponse> = /*@__PURE__*/
  messageDesc(file_document, 2);

/**
 * @generated from message document.DeleteDocumentRequest
 */
export type DeleteDocumentRequest = Message<"document.DeleteDocumentRequest"> & {
  /**
   * @generated from field: string document_id = 1;
   */
  documentId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message document.DeleteDocumentRequest.
 * Use `create(DeleteDocumentRequestSchema)` to create a new message.
 */
export const DeleteDocumentRequestSchema: GenMessage<DeleteDocumentRequest> = /*@__PURE__*/
  messageDesc(file_document, 3);

/**
 * @generated from message document.DeleteDocumentResponse
 */
export type DeleteDocumentResponse = Message<"document.DeleteDocumentResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message document.DeleteDocumentResponse.
 * Use `create(DeleteDocumentResponseSchema)` to create a new message.
 */
export const DeleteDocumentResponseSchema: GenMessage<DeleteDocumentResponse> = /*@__PURE__*/
  messageDesc(file_document, 4);

/**
 * @generated from message document.Document
 */
export type Document = Message<"document.Document"> & {
  /**
   * @generated from field: string document_id = 1;
   */
  documentId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * @generated from field: string topic_id = 4;
   */
  topicId: string;

  /**
   * @generated from field: string topic_name = 5;
   */
  topicName: string;

  /**
   * @generated from field: string uploaded_at = 6;
   */
  uploadedAt: string;
};

/**
 * Describes the message document.Document.
 * Use `create(DocumentSchema)` to create a new message.
 */
export const DocumentSchema: GenMessage<Document> = /*@__PURE__*/
  messageDesc(file_document, 5);

/**
 * @generated from message document.DocumentResponse
 */
export type DocumentResponse = Message<"document.DocumentResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: document.Document document = 3;
   */
  document?: Document | undefined;
};

/**
 * Describes the message document.DocumentResponse.
 * Use `create(DocumentResponseSchema)` to create a new message.
 */
export const DocumentResponseSchema: GenMessage<DocumentResponse> = /*@__PURE__*/
  messageDesc(file_document, 6);

/**
 * @generated from message document.ListDocumentsRequest
 */
export type ListDocumentsRequest = Message<"document.ListDocumentsRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string topic_id = 2;
   */
  topicId: string;
};

/**
 * Describes the message document.ListDocumentsRequest.
 * Use `create(ListDocumentsRequestSchema)` to create a new message.
 */
export const ListDocumentsRequestSchema: GenMessage<ListDocumentsRequest> = /*@__PURE__*/
  messageDesc(file_document, 7);

/**
 * @generated from message document.ListDocumentsResponse
 */
export type ListDocumentsResponse = Message<"document.ListDocumentsResponse"> & {
  /**
   * @generated from field: repeated document.Document documents = 1;
   */
  documents: Document[];
};

/**
 * Describes the message document.ListDocumentsResponse.
 * Use `create(ListDocumentsResponseSchema)` to create a new message.
 */
export const ListDocumentsResponseSchema: GenMessage<ListDocumentsResponse> = /*@__PURE__*/
  messageDesc(file_document, 8);

/**
 * @generated from service document.DocumentService
 */
export const DocumentService: GenService<{
  /**
   * @generated from rpc document.DocumentService.UploadDocument
   */
  uploadDocument: {
    methodKind: "unary";
    input: typeof UploadDocumentRequestSchema;
    output: typeof DocumentResponseSchema;
  },
  /**
   * @generated from rpc document.DocumentService.DownloadDocument
   */
  downloadDocument: {
    methodKind: "unary";
    input: typeof DownloadDocumentRequestSchema;
    output: typeof DownloadDocumentResponseSchema;
  },
  /**
   * @generated from rpc document.DocumentService.ListDocuments
   */
  listDocuments: {
    methodKind: "unary";
    input: typeof ListDocumentsRequestSchema;
    output: typeof ListDocumentsResponseSchema;
  },
  /**
   * @generated from rpc document.DocumentService.DeleteDocument
   */
  deleteDocument: {
    methodKind: "unary";
    input: typeof DeleteDocumentRequestSchema;
    output: typeof DeleteDocumentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_document, 0);

