// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file topic.proto (package topic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file topic.proto.
 */
export const file_topic: GenFile = /*@__PURE__*/
  fileDesc("Cgt0b3BpYy5wcm90bxIFdG9waWMiMwoSQ3JlYXRlVG9waWNSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkSDAoEbmFtZRgCIAEoCSJPChVDcmVhdGVTdWJUb3BpY1JlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCRIXCg9wYXJlbnRfdG9waWNfaWQYAiABKAkSDAoEbmFtZRgDIAEoCSI3ChJEZWxldGVUb3BpY1JlcXVlc3QSEAoIdG9waWNfaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCSI3ChNEZWxldGVUb3BpY1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSJTCgVUb3BpYxIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg8KB3VzZXJfaWQYAyABKAkSHwoJc3VidG9waWNzGAQgAygLMgwudG9waWMuVG9waWMiTgoNVG9waWNSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSGwoFdG9waWMYAyABKAsyDC50b3BpYy5Ub3BpYyIkChFMaXN0VG9waWNzUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJIjIKEkxpc3RUb3BpY3NSZXNwb25zZRIcCgZ0b3BpY3MYASADKAsyDC50b3BpYy5Ub3BpYzKdAgoMVG9waWNTZXJ2aWNlEj4KC0NyZWF0ZVRvcGljEhkudG9waWMuQ3JlYXRlVG9waWNSZXF1ZXN0GhQudG9waWMuVG9waWNSZXNwb25zZRJECg5DcmVhdGVTdWJUb3BpYxIcLnRvcGljLkNyZWF0ZVN1YlRvcGljUmVxdWVzdBoULnRvcGljLlRvcGljUmVzcG9uc2USRAoLRGVsZXRlVG9waWMSGS50b3BpYy5EZWxldGVUb3BpY1JlcXVlc3QaGi50b3BpYy5EZWxldGVUb3BpY1Jlc3BvbnNlEkEKCkxpc3RUb3BpY3MSGC50b3BpYy5MaXN0VG9waWNzUmVxdWVzdBoZLnRvcGljLkxpc3RUb3BpY3NSZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message topic.CreateTopicRequest
 */
export type CreateTopicRequest = Message<"topic.CreateTopicRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message topic.CreateTopicRequest.
 * Use `create(CreateTopicRequestSchema)` to create a new message.
 */
export const CreateTopicRequestSchema: GenMessage<CreateTopicRequest> = /*@__PURE__*/
  messageDesc(file_topic, 0);

/**
 * @generated from message topic.CreateSubTopicRequest
 */
export type CreateSubTopicRequest = Message<"topic.CreateSubTopicRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string parent_topic_id = 2;
   */
  parentTopicId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message topic.CreateSubTopicRequest.
 * Use `create(CreateSubTopicRequestSchema)` to create a new message.
 */
export const CreateSubTopicRequestSchema: GenMessage<CreateSubTopicRequest> = /*@__PURE__*/
  messageDesc(file_topic, 1);

/**
 * @generated from message topic.DeleteTopicRequest
 */
export type DeleteTopicRequest = Message<"topic.DeleteTopicRequest"> & {
  /**
   * @generated from field: string topic_id = 1;
   */
  topicId: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;
};

/**
 * Describes the message topic.DeleteTopicRequest.
 * Use `create(DeleteTopicRequestSchema)` to create a new message.
 */
export const DeleteTopicRequestSchema: GenMessage<DeleteTopicRequest> = /*@__PURE__*/
  messageDesc(file_topic, 2);

/**
 * @generated from message topic.DeleteTopicResponse
 */
export type DeleteTopicResponse = Message<"topic.DeleteTopicResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message topic.DeleteTopicResponse.
 * Use `create(DeleteTopicResponseSchema)` to create a new message.
 */
export const DeleteTopicResponseSchema: GenMessage<DeleteTopicResponse> = /*@__PURE__*/
  messageDesc(file_topic, 3);

/**
 * @generated from message topic.Topic
 */
export type Topic = Message<"topic.Topic"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: repeated topic.Topic subtopics = 4;
   */
  subtopics: Topic[];
};

/**
 * Describes the message topic.Topic.
 * Use `create(TopicSchema)` to create a new message.
 */
export const TopicSchema: GenMessage<Topic> = /*@__PURE__*/
  messageDesc(file_topic, 4);

/**
 * @generated from message topic.TopicResponse
 */
export type TopicResponse = Message<"topic.TopicResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: topic.Topic topic = 3;
   */
  topic?: Topic | undefined;
};

/**
 * Describes the message topic.TopicResponse.
 * Use `create(TopicResponseSchema)` to create a new message.
 */
export const TopicResponseSchema: GenMessage<TopicResponse> = /*@__PURE__*/
  messageDesc(file_topic, 5);

/**
 * @generated from message topic.ListTopicsRequest
 */
export type ListTopicsRequest = Message<"topic.ListTopicsRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message topic.ListTopicsRequest.
 * Use `create(ListTopicsRequestSchema)` to create a new message.
 */
export const ListTopicsRequestSchema: GenMessage<ListTopicsRequest> = /*@__PURE__*/
  messageDesc(file_topic, 6);

/**
 * @generated from message topic.ListTopicsResponse
 */
export type ListTopicsResponse = Message<"topic.ListTopicsResponse"> & {
  /**
   * @generated from field: repeated topic.Topic topics = 1;
   */
  topics: Topic[];
};

/**
 * Describes the message topic.ListTopicsResponse.
 * Use `create(ListTopicsResponseSchema)` to create a new message.
 */
export const ListTopicsResponseSchema: GenMessage<ListTopicsResponse> = /*@__PURE__*/
  messageDesc(file_topic, 7);

/**
 * @generated from service topic.TopicService
 */
export const TopicService: GenService<{
  /**
   * @generated from rpc topic.TopicService.CreateTopic
   */
  createTopic: {
    methodKind: "unary";
    input: typeof CreateTopicRequestSchema;
    output: typeof TopicResponseSchema;
  },
  /**
   * @generated from rpc topic.TopicService.CreateSubTopic
   */
  createSubTopic: {
    methodKind: "unary";
    input: typeof CreateSubTopicRequestSchema;
    output: typeof TopicResponseSchema;
  },
  /**
   * @generated from rpc topic.TopicService.DeleteTopic
   */
  deleteTopic: {
    methodKind: "unary";
    input: typeof DeleteTopicRequestSchema;
    output: typeof DeleteTopicResponseSchema;
  },
  /**
   * @generated from rpc topic.TopicService.ListTopics
   */
  listTopics: {
    methodKind: "unary";
    input: typeof ListTopicsRequestSchema;
    output: typeof ListTopicsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_topic, 0);

